sonar.projectName=linux-autoconfig-gh-actions-sc
sonar.projectKey=sonarsource-cfamily-examples_linux-autoconfig-gh-actions-sc
sonar.organization=sonarsource-cfamily-examples
sonar.projectVersion=1.0

# =====================================================
#   Properties that will be shared amongst all modules
# =====================================================

# SQ standard properties
sonar.sources=src
sonar.sourceEncoding=UTF-8

# There is no need to provide the compile-commands property when using the AutoConfig mode
# sonar.cfamily.compile-commands=bw-output/compile_commands.json
